name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # REQUIRED!!!

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        env:
          # Use GitHub secrets for production builds
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Copy CNAME
        run: cp public/CNAME dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ''  # DONT TOUCH THANKS!
